config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  concern :activeable do
    post :toggle_is_active, on: :member
  end

  devise_path_names = {
    sign_in: 'login',
    sign_out: 'logout',
    password: 'secret',
    confirmation: 'verification'
  }

  # Admins
  devise_for :admins,
             controllers: {
                 sessions: 'hq/sessions',
                 registrations: 'hq/registrations',
                 passwords: 'hq/passwords'
             },
             path: 'hq',
             path_names: devise_path_names

  as :admin do
    get 'hq/edit' => 'hq/registrations#edit', as: 'edit_admin_registration'
    put 'hq' => 'hq/registrations#update', as: 'admin_registration'
  end

  namespace :hq do
    root to: 'dashboard#index'
    resources :dashboard, only: %i[index]
    resources :admins, concerns: %i[activeable]
    resources :users, concerns: %i[activeable]
    resources :audits, only: %i[index show]
  end

  # Users
  devise_for :users,
             controllers: {
                 sessions: 'user/sessions',
                 registrations: 'user/registrations',
                 passwords: 'user/passwords'
             },
             path: 'user',
             path_names: devise_path_names

  as :user do
    get 'user/edit' => 'user/registrations#edit', as: 'edit_user_profile_registration'
    put 'user' => 'user/registrations#update', as: 'user_profile_registration'
  end

  namespace :user do
    root to: 'dashboard#index'
    resources :dashboard, only: %i[index]
    resources :profile, only: %i[show edit update]
  end

  # Common pages
  root to: 'welcome#index'

  resources :welcome, path: '', only: %i[index] do
    get :about, on: :collection
    get :contact, on: :collection
  end

  # devise_for :admins
  # devise_for :users
  # ========== Sidekiq ==========
  if Rails.env.production?
    Sidekiq::Web.use Rack::Auth::Basic do |username, password|
      username == 'sidekiq' && password == 'sidekiq'
    end
  end
  mount Sidekiq::Web, at: '/sidekiq'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  match '*unmatched_route', to: 'application#page_not_found', via: :all unless Rails.env.development?
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  include PasswordCreatable

  # Scopes
  scope :active, -> { where(is_active: true) }

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :trackable,
         :validatable

  # Send devise emails with background job
  def send_devise_notification(notification, *args)
    devise_mailer.send(notification, self, *args).deliver_later
  end

  # Helpers
  audited except: [:password]

  # Validations
  validates_presence_of :name, :email, :surname
  validates :email, uniqueness: true

  def active_for_authentication?
    super && is_active
  end

  def full_name
    "#{name} #{surname}"
  end

  private

  def login_info_mailer
    UserMailer
  end
end

app/controllers/hq/admins_controller.rb
# frozen_string_literal: true

class Hq::AdminsController < Hq::ApplicationController
  include Activatable

  before_action :set_admin, only: %i[show edit update destroy toggle_is_active]
  add_breadcrumb I18n.t('activerecord.models.admins'), :hq_admins_path

  def index
    @search = Admin.order(id: :desc).search(params[:q])
    @admins = @search.result(distinct: true).paginate(page: params[:page])
    respond_with(@admins)
  end

  def show
    add_breadcrumb @admin.name, hq_admin_path(@admin)
    respond_with(@admin)
  end

  def new
    add_breadcrumb t('view.tooltips.new'), new_hq_admin_path
    @admin = Admin.new
    respond_with(@admin)
  end

  def edit
    add_breadcrumb @admin.name, hq_admin_path(@admin)
    add_breadcrumb t('view.tooltips.edit'), edit_hq_admin_path
  end

  def create
    @admin = Admin.new(admin_params)
    @admin.save
    respond_with(:hq, @admin)
  end

  def update
    @admin.update(admin_params)
    respond_with(:hq, @admin)
  end

  def destroy
    @admin.destroy
    respond_with(:hq, @admin, location: request.referer)
  end

  def toggle_is_active
    activation_toggle(@admin)
    respond_with(:hq, @admin, location: request.referer)
  end

  private

  def set_admin
    @admin = Admin.find(params[:id])
  end

  def admin_params
    params.require(:admin).permit(:email, :name, :surname)
  end
end

app/controllers/hq/application_controller.rb
# frozen_string_literal: true

class Hq::ApplicationController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_audit_user
  layout 'hq/application'
  self.responder = ApplicationResponder

  private

  def set_audit_user
    Audited.current_user_method = :current_admin
  end
end

app/controllers/hq/audits_controller.rb
# frozen_string_literal: true

class Hq::AuditsController < Hq::ApplicationController
  add_breadcrumb I18n.t('activerecord.models.audits'), :hq_audits_path

  def index
    @search = Audit.includes(:user).reorder('id DESC').search(params[:q])
    @audits = @search.result(distinct: true).paginate(page: params[:page])
    @auditable_types = Audit.select('auditable_type').group('auditable_type').reorder('')
  end

  def show
    @audit = Audit.find(params[:id])
    add_breadcrumb @audit.id, hq_audit_path(id: @audit)
  end
end

app/controllers/hq/dashboard_controller.rb
# frozen_string_literal: true

class Hq::DashboardController < Hq::ApplicationController
  add_breadcrumb I18n.t('view.dock.dashboard'), :hq_dashboard_index_path

  def index; end
end

app/controllers/hq/passwords_controller.rb
# frozen_string_literal: true

class Hq::PasswordsController < Devise::PasswordsController
  layout 'hq/login'

  private

  def after_resetting_password_path_for(_resource)
    hq_root_path
  end
end

app/controllers/hq/registrations_controller.rb
# frozen_string_literal: true

class Hq::RegistrationsController < Devise::RegistrationsController
  layout 'hq/application'
  before_action :authenticate_admin!
  before_action :redirect_admin, only: %i[new create destroy]
  add_breadcrumb I18n.t('view.dock.dashboard'), :hq_dashboard_index_path

  def edit
    add_breadcrumb I18n.t('view.title.edit', resource_name: Admin.model_name.human)
  end

  private

  def redirect_admin
    redirect_to hq_root_path
  end

  def after_update_path_for(_resource)
    hq_root_path
  end
end

app/controllers/hq/sessions_controller.rb
# frozen_string_literal: true

class Hq::SessionsController < Devise::SessionsController
  layout 'hq/login'

  private

  # Overwriting the sign_out redirect path method
  def after_sign_in_path_for(_resource_or_scope)
    hq_root_path
  end

  # Overwriting the sign_out redirect path method
  def after_sign_out_path_for(_resource_or_scope)
    new_admin_session_path
  end
end

app/controllers/hq/users_controller.rb
# frozen_string_literal: true

class Hq::UsersController < Hq::ApplicationController
  include Activatable

  before_action :set_user, only: %i[show edit update destroy toggle_is_active]
  add_breadcrumb I18n.t('activerecord.models.users'), :hq_users_path

  def index
    @search = User.order(id: :desc).search(params[:q])
    @users = @search.result(distinct: true).paginate(page: params[:page])
    respond_with(@users)
  end

  def show
    add_breadcrumb @user.name, hq_user_path(@user)
    respond_with(@user)
  end

  def new
    add_breadcrumb t('view.tooltips.new'), new_hq_user_path
    @user = User.new
    respond_with(@user)
  end

  def edit
    add_breadcrumb @user.name, hq_user_path(@user)
    add_breadcrumb t('view.tooltips.edit'), edit_hq_user_path
  end

  def create
    @user = User.new(user_params)
    @user.save
    respond_with(:hq, @user)
  end

  def update
    @user.update(user_params)
    respond_with(:hq, @user)
  end

  def destroy
    @user.destroy
    respond_with(:hq, @user, location: request.referer)
  end

  def toggle_is_active
    activation_toggle(@user)
    respond_with(:hq, @user, location: request.referer)
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :name, :surname, :time_zone)
  end
end

app/controllers/user/application_controller.rb
# frozen_string_literal: true

class User::ApplicationController < ApplicationController
  layout 'application'
  before_action :authenticate_user!
  before_action :set_user_time_zone
  self.responder = ApplicationResponder

  protected

  def set_user_time_zone
    time_zone = current_user.time_zone
    Time.zone = time_zone if time_zone.present?

    # Set audit current user
    Audited.current_user_method = :current_user
  end
end

app/controllers/user/dashboard_controller.rb
# frozen_string_literal: true

class User::DashboardController < User::ApplicationController
  add_breadcrumb I18n.t('view.dock.dashboard'), :user_dashboard_index_path

  def index; end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  private

  def after_resetting_password_path_for(_resource)
    user_root_path
  end
end

app/controllers/user/profile_controller.rb
# frozen_string_literal: true

class User::ProfileController < User::ApplicationController
  before_action :set_profile, only: %i[show edit update]
  add_breadcrumb I18n.t('view.dock.profile'), :user_profile_path

  def show
    add_breadcrumb @profile.full_name, user_profile_path
    respond_with(:user, @profile)
  end

  def edit
    add_breadcrumb t('view.tooltips.edit'), edit_user_profile_path
  end

  def update
    @profile.update(profile_params)
    respond_with(:user, @profile, location: user_profile_path)
  end

  private

  def set_profile
    @profile = current_user
  end

  def profile_params
    params.require(:user).permit(:name, :surname, :time_zone)
  end
end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  before_action :authenticate_user!, except: %i[new create]
  before_action :redirect_user, only: %i[destroy]
  add_breadcrumb I18n.t('activerecord.models.user'), :user_root_path

  def edit; end

  private

  def redirect_user
    redirect_to user_root_path
  end

  def after_update_path_for(_resource)
    user_root_path
  end
end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  private

  # Overwriting the sign_out redirect path method
  def after_sign_in_path_for(_resource_or_scope)
    user_root_path
  end

  # Overwriting the sign_out redirect path method
  def after_sign_out_path_for(_resource_or_scope)
    new_user_session_path
  end
end

app/views/hq/users/_blank.html.haml
- if params[:q].present?
  = render 'list', contents: contents, search: search
- else
  .alert.alert-warning
    %p
      %h3= t('view.there_is_no_data', resource: User.model_name.human.downcase)
      = link_to new_hq_user_path, class: 'btn btn-primary' do
        = t('view.actions.new', resource_name: User.model_name.human)
        = t('view.btn.add')

app/views/hq/users/_filters.html.haml
.row
  .col
    = link_to hq_users_path(q: { is_active_true: 1 }), class: 'btn btn-success' do
      = t('view.active')
      %span.badge= User.where(is_active: true).count
    = link_to hq_users_path(q: { is_active_false: 1 }), class: 'btn btn-warning' do
      = t('view.passive')
      %span.badge= User.where(is_active: false).count
    - if query_present?(%w[is_active_true is_active_false name_or_surname_cont])
      = link_to hq_users_path, class: 'btn btn-info' do
        = t('view.all')
        %span.badge= User.count
  .col
    .float-right
      = search_form_for [:hq, search],
                        builder: SimpleForm::FormBuilder,
                        html: { class: 'form-inline', data: { turboform: true } } do |f|
        .float-right
          .input-group
            = f.input_field :name_or_surname_cont,
                            label: false,
                            class: 'form-control',
                            placeholder: t('view.quick_search')
            %span.input-group-btn
              = button_tag(class: 'btn btn-primary') do
                %i.fas.fa-search

app/views/hq/users/_form.html.haml
.card
  .card-header
    %i.fas.fa-edit
    = yield :form_title
  .card-body
    = simple_form_for([:hq, user]) do |f|
      = f.error_notification

      .form-inputs
        = f.input :name
        = f.input :surname
        = f.input :email

      .form-actions
        - text = user.persisted? ? t('view.btn.update') : t('view.btn.add')
        = f.button :submit, text, class: 'btn btn-primary'
        = link_to t('view.cancel'), hq_users_path, class: 'btn'

app/views/hq/users/_list.html.haml
.card-body.filters
  = render 'filters', search: search
%table.table
  %thead
    %tr
      %th{ data: { breakpoints: 'xs' } }
        = sort_link(search, :id, t('activerecord.attributes.user.id'))
      %th= sort_link(search, :name, t('activerecord.attributes.user.name'))
      %th{ data: { breakpoints: 'xs' } }
        = sort_link(search, :email, t('activerecord.attributes.user.email'))
      %th{ data: { breakpoints: 'xs sm' } }
        = sort_link search,
                    :current_sign_in_at,
                    t('activerecord.attributes.user.current_sign_in_at')
      %th{ data: { breakpoints: 'xs sm' } }
        = sort_link(search, :last_sign_in_at, t('activerecord.attributes.user.last_sign_in_at'))
      %th{ data: { breakpoints: 'xs sm' } }
        = sort_link(search, :is_active, t('activerecord.attributes.user.is_active'))
      %th{ data: { breakpoints: 'xs' } }= t('view.table_actions')
  %tbody.users
    = render partial: 'user', collection: contents, as: :user

app/views/hq/users/_user.html.haml
%tr{ class: user.is_active ? 'active' : 'passive' }
  %td= user.id
  %td= user.full_name
  %td= mail_to user.email, user.email
  %td= l user.current_sign_in_at if user.current_sign_in_at.present?
  %td= l user.last_sign_in_at if user.last_sign_in_at.present?
  %td= user.is_active ? t('view.active') : t('view.passive')
  %td.action
    = link_to [:hq, user],
              class: 'btn btn-success btn-sm',
              data: { toggle: :tooltip },
              title: t('view.tooltips.zoom') do
      %i.fas.fa-search-plus
    = link_to edit_hq_user_path(user),
              class: 'btn btn-info btn-sm',
              data: { toggle: :tooltip },
              title: t('view.tooltips.edit') do
      %i.fas.fa-edit
    = link_to [:hq, user],
              class: 'btn btn-danger btn-sm',
              method: :delete,
              data: { confirm: t('view.tooltips.are_you_sure'), toggle: :tooltip },
              title: t('view.tooltips.delete') do
      %i.fas.fa-trash
    - if user.is_active
      = link_to toggle_is_active_hq_user_path(user),
                class: 'btn btn-danger btn-sm',
                method: :post,
                data: { toggle: :tooltip },
                title: t('view.make_passive') do
        %i.fas.fa-ban
    - else
      = link_to toggle_is_active_hq_user_path(user),
                class: 'btn btn-info btn-sm',
                method: :post,
                data: { toggle: :tooltip },
                title: t('view.make_active') do
        %i.fas.fa-check

app/views/hq/users/edit.html.haml
- content_for :form_title do
  = t('view.title.edit', resource_name: User.model_name.human)
= render 'form', user: @user

app/views/hq/users/index.html.haml
- content_for :toolbar do
  = link_to new_hq_user_path, class: 'btn btn-default btn-primary' do
    %i.fas.fa-plus
    = t('view.actions.new', resource_name: User.model_name.human)

.card
  .card-header
    %i.fas.fa-table
    = t('activerecord.models.users')
    .float-right
      .btn-group
        %a.btn{ href: hq_users_path, data: { toggle: 'tooltip' }, title: t('view.reload') }
          %i.fas.fa-sync
      .badge.badge-pill.badge-secondary= @users.total_entries
  = blankable(@users, @search)
  .card-footer
    .pagination.pagination-sm
      = will_paginate @users, renderer: BootstrapPagination::Rails, bootstrap: 3

app/views/hq/users/new.html.haml
- content_for :form_title do
  = t('view.form.new_title', resource_name: User.model_name.human)
.alert.alert-info
  = t('view.create_resource_mail_info', resource: User.model_name.human.downcase)
= render 'form', user: @user

app/views/hq/users/show.html.haml
- content_for :toolbar do
  = link_to edit_hq_user_path(@user), class: 'btn btn-default btn-primary' do
    %i.fas.fa-pencil
    = t('view.edit')
.card
  .card-header
    %i.fas.fa-edit
    = t('view.tooltips.show', resource_name: User.model_name.human)
  .card-body
    = show_for @user do |s|
      = s.attribute :name
      = s.attribute :surname
      = s.attribute :email do
        = mail_to @user.email, @user.email
      = s.attribute :is_active
      = s.attribute :current_sign_in_at
      = s.attribute :last_sign_in_at
      = s.attribute :created_at
      = s.attribute :updated_at