config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  concern :activeable do
    post :toggle_is_active, on: :member
  end

  devise_path_names = {
    sign_in: 'login',
    sign_out: 'logout',
    password: 'secret',
    confirmation: 'verification'
  }

  # Admins
  devise_for :admins,
             controllers: {
                 sessions: 'hq/sessions',
                 registrations: 'hq/registrations',
                 passwords: 'hq/passwords'
             },
             path: 'hq',
             path_names: devise_path_names

  as :admin do
    get 'hq/edit' => 'hq/registrations#edit', as: 'edit_admin_registration'
    put 'hq' => 'hq/registrations#update', as: 'admin_registration'
  end

  namespace :hq do
    root to: 'dashboard#index'
    resources :dashboard, only: %i[index]
    resources :admins, concerns: %i[activeable]
    resources :users, concerns: %i[activeable]
    resources :audits, only: %i[index show]
  end

  # Users
  devise_for :users,
             controllers: {
                 sessions: 'user/sessions',
                 registrations: 'user/registrations',
                 passwords: 'user/passwords'
             },
             path: 'user',
             path_names: devise_path_names

  as :user do
    get 'user/edit' => 'user/registrations#edit', as: 'edit_user_profile_registration'
    put 'user' => 'user/registrations#update', as: 'user_profile_registration'
  end

  namespace :user do
    root to: 'dashboard#index'
    resources :dashboard, only: %i[index]
    resources :profile, only: %i[show edit update]
  end

  # Common pages
  root to: 'welcome#index'

  resources :welcome, path: '', only: %i[index] do
    get :about, on: :collection
    get :contact, on: :collection
  end

  # devise_for :admins
  # devise_for :users
  # ========== Sidekiq ==========
  if Rails.env.production?
    Sidekiq::Web.use Rack::Auth::Basic do |username, password|
      username == 'sidekiq' && password == 'sidekiq'
    end
  end
  mount Sidekiq::Web, at: '/sidekiq'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  match '*unmatched_route', to: 'application#page_not_found', via: :all unless Rails.env.development?
end

app/views/layouts/partials/_messages.html.haml
- flash.each do |key, value|
  - if key.to_s == 'notice'
    - key = 'success'
  - if key.to_s == 'alert'
    - key = 'danger'
  .alert.alert-dismissable.message{ class: "alert-#{key}" }
    - if key.to_s == 'danger' || key.to_s == 'warning'
      %i.fas.fa-exclamation-triangle.fa-lg
    - else
      %i.fas.fa-smile.fa-lg
    = value

app/views/layouts/partials/_navbar.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light
  %a.navbar-brand{ href: root_path }
    %i.fas.fa-home
    = 'Hello_world'
  %button.navbar-toggler{ 'aria-controls' => 'navbar-nav-dropdown',
                          'aria-expanded' => 'false',
                          'aria-label' => 'Toggle navigation',
                          'data-target' => '#navbar-nav-dropdown',
                          'data-toggle' => 'collapse',
                          type: 'button' }
    %span.navbar-toggler-icon
  .collapse.navbar-collapse#navbar-nav-dropdown
    %ul.navbar-nav.ml-auto
      %li.nav-item
        = link_to about_welcome_index_path, class: 'nav-link' do
          = t('view.welcome.navbar.about')
      %li.nav-item
        = link_to contact_welcome_index_path, class: 'nav-link' do
          = t('view.welcome.navbar.contact')
      - if user_signed_in?
        %li.nav-item
          = link_to destroy_user_session_path, class: 'nav-link', method: :delete do
            %i.fas.fa-sign-out-alt
            = t('view.navbar.sign_out')
        %li.nav-item
          = link_to user_profile_path(current_user), class: 'nav-link' do
            %i.fas.fa-user
            = t('view.navbar.profile')
      - else
        %li.nav-item
          = link_to new_user_session_path, class: 'nav-link' do
            %i.fas.fa-sign-in-alt{ 'aria-hidden' => 'true' }
            = t('view.navbar.signin')
        %li.nav-item
          = link_to new_user_registration_path, class: 'nav-link' do
            %i.fas.fa-user-plus{ 'aria-hidden' => 'true' }
            = t('view.navbar.signup')